config/routes.rb
Rails.application.routes.draw do
  resources :subscribers do
    collection do
      get 'unsubscribe'
    end
  end
  devise_for :users
  resources :testimonials
  get 'home/index'
  post '/contact' => 'home#contact'

  resources :articles

  
  root to: "home#index"
  
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :new, :update, :destroy]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.order('created_at DESC')
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)


    respond_to do |format|
      if @article.save
        Subscriber.all.each do |subscriber|
          PostMailer.new_post_email(subscriber.email, @article).deliver_later
        end
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.order('created_at DESC')
    @testimonials = Testimonial.order('created_at DESC')
  end
  def contact
    ContactMailer.new_contact_email(params[:email], params[:message], params[:name]).deliver_later
    redirect_to root_path, notice: 'Message was successfully sent.'
  end
  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:email, :message, :name)
    end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :set_subscriber, only: [:show, :edit, :update, :destroy]
  
  def unsubscribe
    subscriber = Subscriber.find_by(email: params[:email])
    subscriber.try(:destroy)
    respond_to do |format|
      format.html { redirect_to articles_url, notice: subscriber ? 'Subscriber was successfully destroyed.' : 'Subscriber was already deleted.'}
      format.json { head :no_content }
    end
  end  

  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully created.' }
        format.json { render :show, status: :created, location: @subscriber }
      else
        format.html { render :new }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribers/1
  # PATCH/PUT /subscribers/1.json
  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscriber }
      else
        format.html { render :edit }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber.destroy
    respond_to do |format|
      format.html { redirect_to subscribers_url, notice: 'Subscriber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscriber_params
      params.require(:subscriber).permit(:email)
    end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :new, :update, :destroy]
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]

  # GET /testimonials
  # GET /testimonials.json
  def index
    @testimonials = Testimonial.all
  end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
  end

  # GET /testimonials/new
  def new
    @testimonial = Testimonial.new
  end

  # GET /testimonials/1/edit
  def edit
  end

  # POST /testimonials
  # POST /testimonials.json
  def create
    @testimonial = Testimonial.new(testimonial_params)

    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully created.' }
        format.json { render :show, status: :created, location: @testimonial }
      else
        format.html { render :new }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testimonials/1
  # PATCH/PUT /testimonials/1.json
  def update
    respond_to do |format|
      if @testimonial.update(testimonial_params)
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
        format.json { render :show, status: :ok, location: @testimonial }
      else
        format.html { render :edit }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
  def destroy
    @testimonial.destroy
    respond_to do |format|
      format.html { redirect_to testimonials_url, notice: 'Testimonial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testimonial_params
      params.require(:testimonial).permit(:quote, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/articles/edit.html.erb
<div class="row" style="margin-top:40px;">
    <div class="large-12 columns">
        <h1 style="letter-spacing:0;margin-top:0;margin-bottom:0;">editing post</h1>
        <%= render 'form' %>
        
        <%= link_to 'Show', @article, :class => 'small button radius secondary' %>
        <%= link_to 'Back', articles_path, :class => 'small button radius secondary' %>
    </div>
</div>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>
<!-- www9.wixdns.net -->
<div class="image">
    <%= link_to image_tag('IMG_3230.JPG', style: 'opacity:0.6;position:relative;width:100%;'), home_index_path %>
    <!--<h1 style="position: absolute; top:200px; left:30%; width:85%; ">lana's blog</h1>-->
</div>


<!--<div class="row" style="max-width:none;background-color:#3F3F3F;height:initial;">-->
<!--    <div class="large-12 columns">-->
<!--        <h1 class="text-center">lana's blog</h1>-->
<!--    </div>-->
<!--</div>-->

<br>
<div class="row">
    <div class="large-12 columns">
        <div class="panel callout radius">
            <h3 style="font-weight:bold;">Want to subscribe to Lana's posts?</h3>
            <p style="font-weight:bold;"><%= link_to "Click here to subscribe.", new_subscriber_path %></p>
        </div>
    </div>
</div>
<br>
<% @articles.each_with_index do |article, index| %>
    <div class="row" style="padding-left:8%;padding-right:8%;padding-bottom:1%;padding-top:1%;">
        <div class="large-12 columns">
            <p class="float:right;"><%= article.created_at.strftime("Posted %b %d, %Y (%l:%M%P)") %></p>
            <h2 style="margin-bottom:3%;margin-top:0;"><%= article.title %></h2>
            <%= raw(article.content) %>
            <% if user_signed_in? %>
                <ul class="button-group round" style="margin-top:10px;float:right;">
                  <li><%= link_to 'Show', article, :class => 'tiny button secondary' %></li>
                  <li><%= link_to 'Edit', edit_article_path(article), :class => 'tiny button secondary' %></li>
                  <li><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'tiny button secondary' %></li>
                </ul>
            <% end %>
            <% if @articles.length-1 != index %>
                <hr>
            <% end %>
        </div>
    </div>
<% end %>

<br>

<% if user_signed_in? %>
    <div class="row">
        <div class="large-12 columns">
            <div style="margin-left:6.5%;"><%= link_to 'New Article', new_article_path, :class => 'button radius secondary' %></div>
        </div>
    </div>
<% end %>

app/views/articles/new.html.erb
<div class="row" style="margin-top:40px;">
    <div class="large-12 columns">
        <h1 style="letter-spacing:0;margin-top:0;margin-bottom:0;">new post</h1>
        <%= render 'form' %>
        <%= link_to 'Back', articles_path, :class => 'small button radius secondary' %>
    </div>
</div>

app/views/articles/show.html.erb
<div class="row" style="margin-top:40px;">
  <div class="large-12 columns">
    <h1 style="letter-spacing:0; margin-top:0;margin-bottom:0;">showing post</h1>
    <p id="notice"><%= notice %></p>
    
    <p>
      <strong>title:</strong>
      <%= @article.title %>
    </p>
    
    <p>
      <strong>content:</strong>
      <%= raw(@article.content) %>
    </p>
    
    <%= link_to 'Edit', edit_article_path(@article), :class => 'small button radius secondary' %>
    <%= link_to 'Back', articles_path, :class => 'small button radius secondary' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <title>Lana Rizika Fitness</title>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <style>
      body * {
        /*border: 1px solid black;*/
      }
    </style>
  </head>
  <script>
    $(document).ready(function() {
        var stickyNavTop = $('.entire-nav').offset().top;
         
        var stickyNav = function(){
        var scrollTop = $(window).scrollTop();
              
        if (scrollTop > stickyNavTop) { 
            $('.entire-nav').addClass('mysticky');
        } else {
            $('.entire-nav').removeClass('mysticky'); 
        }
      };
       
      stickyNav();
       
      $(window).scroll(function() {
          stickyNav();
      });
    });
  </script>
  <body>
    
    <div class="entire-nav" style="top:0;background-color:white;">
      <div class="row" style="margin-right:10px;">
        <div class = "large-3 columns">
          <%= link_to image_tag('lana_logo_crop.jpg', style: 'padding-top: 8px;'), root_path %>
        </div>
        <div class="large-9 columns" style="margin:0;">
          <div class="row" style="padding-bottom:5px;padding-top:5px;">
            <div class="large-10 columns" style="padding:0;width:90.33%;">
              <p class="text-right" style="margin-bottom:0;font-size:1.5em;">lanarizikafitness@gmail.com</p>
              <p class="text-right" style="margin-bottom:0;font-size:1.5em;margin-top:10px;">310.408.4479</p>
            </div>
            <div class="large-2 columns" style="padding:0;margin:0;width:70px;"> 
              <%= link_to image_tag('facebooklogo.png', style: 'position: relative; float:right; width: 30px;'), "https://www.facebook.com/lanarizikafitness/" %>
              <%= link_to image_tag('instagramlogo.png', style: 'position: relative;float:right; margin-right:5px; width: 30px;'), "https://www.instagram.com/lanarizikafitness/" %>
            </div>
          </div>
          <div class="row">
            <div class="large-12 columns" style="padding-left:0; padding-right:0;">
                <div class="top-bar" id="nav-menu">
                  <span data-responsive-toggle="responsive-menu" data-hide-for="medium">
                    <button class="menu-icon dark" type="button" data-toggle></button>
                    <strong style="font-size:17px;">Menu</strong>
                  </span>
                  <div id="responsive-menu">
                    <div class="top-bar-right">
                      <ul class="vertical medium-horizontal menu" data-dropdown-menu>
                        <li><%= link_to 'home', root_path, style: 'font-size:1.5em;' %></li>
                        <!--<li><!%= link_to 'Check teachers', home_index_path(%["#services"]) %></li>-->
                        <li><a href="/#services" style="font-size:1.5em;">services</a></li>
                        <li><a href="/#about" style="font-size:1.5em;">about</a></li>
                        <li><a href="/#testimonials" style="font-size:1.5em;">testimonials</a></li> 
                        <li><a href="/articles" style="font-size:1.5em;">blog</a></li> 
                        <li><a href="/#contact_me" style="font-size:1.5em;">contact</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>
       <!-- <a style="float:right;" href="https://www.instagram.com/lanarizikafitness/">image</a>-->
    </div>
      
      <% if notice %><p class="notice"><%= notice %></p><% end %>
      <% if alert %><p class="alert"><%= alert %></p><% end %>

      <%= yield %>

  </body>
</html>

app/views/pages/about_me.html.erb
<div class="image">
    <%= link_to image_tag('IMG_3229.JPG', style: 'opacity:0.6;position:relative;width:100%;'), home_index_path %>
    <!--<h1 style="position: absolute; top:200px; left:15%; width:85%; ">welcome to lana rizika fitness</h1>-->
</div>


<div class="row">
    <div class="large-12 columns" style="padding-left:8%;padding-right:8%;padding-up:8%;">
        <h2>about</h2>
        <p style="font-size:1.5em;line-height:30px;">
            Years of dance, running, and weight training have kept Lana feeling strong and fit. It was 
            after a brief setback in 2014 (she had a stress fracture in her hip) that she fully understood 
            how vital exercise was to her overall well-being. More importantly, she was inspired to teach 
            others how to make fitness an enjoyable part of life so they too can realize all its physical 
            and mental health benefits. Fitness, she believes, is a game changer.<br><br>
            Lana received her Personal Trainer Certification from NASM and continues her education through 
            classes, seminars, and various training programs. She weight trains several times a week, mixes 
            in cardio workouts, and dedicates time to her new passion, boxing!   </p>
    </div>
</div>

<div class="row">
    <div class="large-12 columns" style="padding-left:8%;padding-right:8%;padding-bottom:5%;">
        <h2>about lana rizka fitness</h2>
        <p style="font-size:1.5em;line-height:30px;"> 
            Lana Rizika Fitness focuses on providing an hour-long personalized workout created specifically 
            to meet the client’s fitness goals.
        </p>
        <p style="font-size:1.5em;line-height:30px;"> 
            She incorporates 3 specialties into these workouts: Strength Training, Interval Training, and 
            Flexibility/Mobility Training.
        </p>
        <p style="font-size:1.5em;line-height:30px;"> 
            <b>Strength Training</b> has multiple benefits and impacts everything from posture to how you 
            pick up a bag of groceries:   
            <ul style="font-size:1.35em;line-height:30px;padding-left:30px;">
                <li>Increase lean muscle mass</li>
                <li>Boost metabolism</li>
                <li>Burn more calories as muscles strengthen - even at rest!</li>
                <li>Tighten core, back, and booty</li>
                <li>Look toned and sculpted</li>
            </ul>
        </p> 
        <p style="font-size:1.5em;line-height:30px;"> 
            <b>Interval Training</b> ratchets up your heart rate so you can:   
            <ul style="font-size:1.35em;line-height:30px;padding-left:30px;">
                <li>Burn fat</li>
                <li>Build your endurance</li>
                <li>Burn more calories in less time</li>
                <li>Increase aerobic capacity</li>
            </ul>
        </p> 
        <p style="font-size:1.5em;line-height:30px;"> 
            <b>Flexibility/Mobility Training</b> will help you:   
            <ul style="font-size:1.35em;line-height:30px;padding-left:30px;">
                <li>Move, stretch, and reach without pain</li>
                <li>Attain full range of motion</li>
                <li>Move more fluidly</li>
                <li>Workout more efficiently</li>
                <li>Improve posture</li>
            </ul>
        </p> 
        <p style="font-size:1.5em;line-height:30px;">
            Lana is passionate about helping clients feel the benefits of physical fitness, which 
            permeate all areas of life. This takes time and commitment, and Lana is here to coach 
            you all the way.  You have the power to create the best version of you!
        </p>
        <p  style="font-size:1.5em;line-height:30px;">
            Lana is based in Manhattan Beach, CA, and trains out of her home gym, at the local park, 
            and at the beach.  
        </p>
    </div>
</div>

app/views/pages/contact_me.html.erb
<div class="row" style="max-width:none;background-color:#3F3F3F;height:initial;">
    <div class="large-12 columns">
        <h1 style="letter-spacing:4px;margin-top:45px;margin-bottom:20px;padding-left:120px;">contact me</h1>
        <p class="contact_me">I would love to hear from you.  Please feel free to contact me:</p>
        <p class="contact_me">Name</p>
        <p class="contact_me">Email</p>
        <p class="contact_me">Message</p>
        <p class="contact_me">Ready to get started?  Click here for a complimentary 1-hour fitness consultation</p>
        <p class="contact_me" style="padding-bottom:30px;font-weight:bold;"><%= link_to "Click to subscribe to blog", new_subscriber_path, :style => 'color:white;font-style:italic;' %></p>
    </div>
</div>

app/views/pages/services.html.erb
<div class="image">
    <%= link_to image_tag('IMG_3224.JPG', style: 'opacity:0.6;position:relative;width:100%;'), home_index_path %>
    <!--<h1 style="position: absolute; top:200px; left:38%; width:100%; ">Services</h1>-->
</div>

<div class="row">
    <div class="small-12 large-6 columns" style="padding-right:8%; padding-left:8%;">
        <h2>private training</h2>
        <p style="font-size:1.5em;line-height:30px;"> 
            1-on-1 coaching session created specifically for each client. Focus is on meeting client’s 
            fitness goals through proper training, technique and nutrition.      
        </p>
    </div>
    <div class="small-12 large-6 columns" style="padding-right:8%; padding-left:8%;">
        <h2>small group training</h2>
        <p style="font-size:1.5em;line-height:30px;"> 
            Small groups of 2-5 people share in the pains and gains of training together – push each 
            other to bring your best to the mat.      
        </p>
    </div>
</div>


<div class="row">
    <div class="small-12 large-6 columns" style="padding-right:8%; padding-left:8%;">
        <h2>stretch</h2>
        <p style="font-size:1.5em;line-height:30px;"> 
            A 30- or 60-minute Stretch session will help improve flexibility and mobility, relieve
            tight muscles, and reduce aches and pains.          
        </p>
    </div>
    <div class="small-12 large-6 columns" style="padding-right:8%; padding-left:8%;">
        <h2>teens</h2>
        <p style="font-size:1.5em;line-height:30px;"> 
            Strength training for teens to increase overall conditioning and ensure balanced muscle 
            development.        
        </p>
    </div>
</div>

<div class="row">
    <div class="large-12 columns" style="padding-right:8%; padding-left:8%;">
        <h2>nutrition counseling</h2>
        <p style="font-size:1.5em;line-height:30px;"> 
            Work together to adjust meals and snacks and create food plans to improve eating habits, 
            lose weight, and feel great.        
        </p>
    </div>
</div>

app/views/pages/user_links.html.erb
<div class="row">
    <div class="large-12 columns">
        <h2>User Links</h2>
    </div>
</div>

app/views/subscribers/edit.html.erb
<div class="row">
    <div class="large-12 columns">
        <h1>editing subscriber</h1>
        
        <%= render 'form' %>
        
        <%= link_to 'Show', @subscriber, :class => 'small button radius secondary' %> 
        <%= link_to 'Back', user_signed_in? ? subscribers_path : articles_path, :class => 'small button radius secondary' %>
        
    </div>
</div>

app/views/subscribers/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <p id="notice"><%= notice %></p>
    
    <h1 style="margin:0;letter-spacing:5px;">subscribers</h1>
    <% if user_signed_in? %>
      <% @subscribers.each do |subscriber| %>
        <div class = "panel">
          <%= subscriber.email %>
          <div class="small button-group" style="float:right;">
            <%= link_to 'Show', subscriber, :class => 'button' %>
            <%= link_to 'Edit', edit_subscriber_path(subscriber), :class => 'button' %>
            <%= link_to 'Destroy', subscriber, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'button'%>
          </div>
        </div>
        <br>
        <br>
        <br>
      <% end %>
      <br>
    <% end %>
    
    
  </div>
</div>

<% if user_signed_in? %>
    <div class="row">
        <div class="large-12 columns">
            <div><%= link_to 'New Subscriber', new_subscriber_path, :class => 'button radius secondary' %></div>
        </div>
    </div>
<% end %>

app/views/subscribers/new.html.erb
<div class="row">
    <div class="large-12 columns">
        <h1 style="margin:0;letter-spacing:5px;">new subscriber</h1>
        
        <%= render 'form' %>

        <% if user_signed_in? %>
            <%= link_to 'Back', subscribers_path, :class => 'small button radius secondary' %>
        <% end %>
    </div>
</div>

app/views/subscribers/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <p id="notice"><%= notice %></p>
    
    <p>
      <strong>email:</strong>
      <%= @subscriber.email %>
    </p>
    
    <%= link_to 'Edit', edit_subscriber_path(@subscriber), :class => 'small button radius secondary' %> 
    <%= link_to 'Back', user_signed_in? ? subscribers_path : articles_path, :class => 'small button radius secondary' %>
    
  </div>
</div>

app/views/testimonials/edit.html.erb
<div class="row" style="margin-top:40px;">
    <div class="large-12 columns">
        <h1 style="letter-spacing:0;margin-top:0;margin-bottom:0;">Editing Testimonial</h1>
        <%= render 'form' %>
        
        <%= link_to 'Show', @testimonial, :class => 'small button radius secondary' %>
        <%= link_to 'Back', testimonials_path, :class => 'small button radius secondary' %>
    </div>
</div>

app/views/testimonials/index.html.erb
<p id="notice"><%= notice %></p>

<div class="image">
    <%= link_to image_tag('weights.JPG', style: 'opacity:0.6;position:relative;width:100%;'), home_index_path %>
    <!--<h1 style="position: absolute; top:200px; left:38%; width:100%; ">Testimonials</h1>-->
</div>

<div class="row" style="margin-top:100px;margin-bottom:10px;">
  <div class="large-12 columns">
    <% @testimonials.each_with_index do |testimonial, index| %>
      <% if index%2==0 %>
        <div class="row">
          <div class="large-6 columns">
            <blockquote><%= testimonial.quote %>
            <cite class="text-right"><%= testimonial.name %></cite></blockquote>
            <% if user_signed_in? %>
            <ul class="button-group round" style="margin-top:10px;float:right;">
              <li><%= link_to 'Show', testimonial, :class => 'tiny button secondary' %></li>
              <li><%= link_to 'Edit', edit_testimonial_path(testimonial), :class => 'tiny button secondary' %></li>
              <li><%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'tiny button secondary' %></li>
            </ul>
            <% end %>
          </div>
      <% else %>
        <div class="large-6 columns">
          <blockquote><%= testimonial.quote %>
          <cite class="text-right"><%= testimonial.name %></cite></blockquote>
          <% if user_signed_in? %>
            <ul class="button-group round" style="margin-top:10px;float:right;">
              <li><%= link_to 'Show', testimonial, :class => 'tiny button secondary' %></li>
              <li><%= link_to 'Edit', edit_testimonial_path(testimonial), :class => 'tiny button secondary' %></li>
              <li><%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'tiny button secondary' %></li>
            </ul>
          <% end %>
        </div>
        </div>
      <% end %>
    <% end %>
    <% if @testimonials.length % 2 == 1 %>
      </div>
    <% end %>
  </div>
</div>

<% if user_signed_in? %>
  <div class="row">
      <div class="large-12 columns">
          <div style="margin-left:7px;"><%= link_to 'New Testimonial', new_testimonial_path, :class => 'button radius secondary' %></div>
      </div>
  </div>
<% end %>

app/views/testimonials/new.html.erb
<div class="row" style="margin-top:40px;">
    <div class="large-12 columns">
        <h1 style="letter-spacing:0;margin-top:0;margin-bottom:0;">New Testimonial</h1>
        <%= render 'form' %>
        <%= link_to 'Back', testimonials_path, :class => 'small button radius secondary' %>
    </div>
</div>

app/views/testimonials/show.html.erb
<div class="row" style="margin-top:40px;">
  <div class="large-12 columns">
    <h1 style="letter-spacing:0; margin-top:0;margin-bottom:0;">Showing Testimonial</h1>
    <p id="notice"><%= notice %></p>
    
    <p>
      <strong>Quote:</strong>
      <%= @testimonial.quote %>
    </p>
    
    <p>
      <strong>Name:</strong>
      <%= @testimonial.name %>
    </p>
    
    <%= link_to 'Edit', edit_testimonial_path(@testimonial), :class => 'small button radius secondary' %>
    <%= link_to 'Back', testimonial_path, :class => 'small button radius secondary' %>
  </div>
</div>